### PR TITLE
POSIX implementation of ExpandPath

### PR DESCRIPTION
**Pull request by alessio**
The function ExpandPath does not implement the tilde expansion as mandated by POSIX, i.e. a tilde-prefix could be followed by a valid login name; in that case, the tilde-prefix shall be replaced by the home directory associated with that login name.

See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html for more information.

:link: [zboto Link](https://app.clickup.com/t/86932kpb3)

### CODE REVIEW

**Comment by jleni** [comment]
Mamma mia! Alessio 🎸 rockstar! nice to you see around man!
This is a part of an internal project, are you planning to use it somehow?

**Comment by alessio** [comment]
> Looks good to me, would improve the testing with assertions

Done, thanks!

**Comment by alessio** [comment]
@jleni gentle bump :)

**Comment by alessio** [comment]
bump :)

**Review by jleni — APPROVED** [review]

**Comment by alessio** [comment]
I fixed the tests. It should be good to go now.

**Comment by alessio** [comment]
Superseded by #36

**Pull request closed without merging**
