### PR TITLE
POSIX implementation of ExpandPath

### PR DESCRIPTION
**Pull request by alessio**
The function ExpandPath does not implement the tilde expansion as mandated by POSIX, i.e. a tilde-prefix could be followed by a valid login name; in that case, the tilde-prefix shall be replaced by the home directory associated with that login name.

See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html for more information.

:link: [zboto Link](https://app.clickup.com/t/8693b5vcm)

### CODE REVIEW

**Comment by alessio** [comment]
@jleni @bizk please review

**Review by bizk — COMMENTED** [review]
Seems OK to me

**Review by lucaslopezf — APPROVED** [review]

**Comment by emmanuelm41** [comment]
@alessio sorry for the long wait. Could you please reopen the PR so that you can sign the CLA? Then I will merge your PR!! Thanks you a lot

**Comment by emmanuelm41** [comment]
@alessio could you please sign the CLA so that I can merge the PR?

**Comment by emmanuelm41** [comment]
@alessio just pinging you again! I want to merge this, but I need the CLA signed. Could you please do it? Thanks!

**Review by emmanuelm41 — APPROVED** [review]

**Pull request merged**
